name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get -y install \
          ccache cmake make g++-multilib gdb \
          pkg-config coreutils python3-pexpect manpages-dev git \
          ninja-build capnproto libcapnp-dev zlib1g-dev
    - name: configure
      run: ./configure
    - name: cmake
      run: cmake --build .
    - name: make check
      run: ctest -j$(nproc) -VV
