name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get -y install \
          ccache cmake g++-multilib gdb \
          manpages-dev \
          ninja-build capnproto libcapnp-dev
    - name: cmake
      run: |
        CC=clang CXX=clang++ cmake -G Ninja 
        cmake --build .
    - name: make check
      run: ctest -j$(nproc) -VV
